title: OaklandVeg
homeURL: http://OaklandVeg.com
tagline: "Oakland Veg's mission is to introduce the Oakland community to the many benefits of a plant-based diet, for our health, animals, and the environment."
permalink: /404.html
google_analytics_token: UA-31063638-1
brand:
  colors:
    blue: '#3FBFBC'
    red: '#EE4823'
    green: '#B5BE24'
    yellow: '#F8C238'
    link: '#3F5ABF'
    blue-hover: '#2a9896'
    red-hover: 'rgb(161, 38, 12)'
  fontface:
    primary: "'Open Sans', sans-serif"  #need to include this as a web font somehow
    primaryweight: 800
    secondary: "'Open Sans', sans-serif" #web font include
    secondaryweight: 300
    body: "'Open Sans', sans-serif"
    bodyweight: 400
assetsDirectory: /assets/
